export const userActionTypes = {
  USERS_REQUEST: "USERS_REQUEST",
  USERS_SUCCESS: "USERS_SUCCESS",
  USERS_FAILED: "USERS_FAILED",
};

export const projectActionTypes = {
  PROJECTS_REQUEST: "PROJECTS_REQUEST",
  PROJECTS_SUCCESS: "PROJECTS_SUCCESS",
  PROJECTS_FAILED: "PROJECTS_FAILED",
};

export const gatewayActionTypes = {
  GATEWAYS_REQUEST: "GATEWAYS_REQUEST",
  GATEWAYS_SUCCESS: "GATEWAYS_SUCCESS",
  GATEWAYS_FAILED: "GATEWAYS_FAILED",
};

export const reportActionTypes = {
  GENERATE_REPORT_REQUEST: "GENERATE_REPORT_REQUEST",
  GENERATE_REPORT_SUCCESS: "GENERATE_REPORT_SUCCESS",
  GENERATE_REPORT_FAILED: "GENERATE_REPORT_FAILED",
  CHANGE_REPORT_PARAMETERS: "CHANGE_REPORT_PARAMETERS",
};
